import { User, Job } from './types';

export const mockUsers: User[] = [
  {
    id: 'f1',
    name: 'Amit Verma',
    role: 'freelancer',
    avatar: 'https://picsum.photos/seed/amit/200/200',
    location: {
      lat: 26.8467,
      lng: 80.9462,
      address: 'Hazratganj, Lucknow',
      pincode: '226001',
    },
    rating: 4.9,
    skills: ['React Native', 'TypeScript', 'Node.js'],
    bio: 'Senior React Developer specializing in high-performance web and mobile applications.',
    verified: true,
  },
  {
    id: 'f2',
    name: 'Priya Sharma',
    role: 'freelancer',
    avatar: 'https://picsum.photos/seed/priya/200/200',
    location: {
      lat: 26.852,
      lng: 80.998,
      address: 'Gomti Nagar, Lucknow',
      pincode: '226010',
    },
    rating: 5.0,
    skills: ['Figma', 'Prototyping', 'Web Design'],
    bio: 'UI/UX Designer with a passion for creating intuitive and beautiful digital experiences.',
    verified: true,
  },
  {
    id: 'f3',
    name: 'Rahul Singh',
    role: 'freelancer',
    avatar: 'https://picsum.photos/seed/rahul_s/200/200',
    location: {
      lat: 26.86,
      lng: 81.01,
      address: 'Indira Nagar, Lucknow',
      pincode: '226016',
    },
    rating: 4.7,
    skills: ['Python', 'Django', 'PostgreSQL'],
    bio: 'Full Stack Engineer with extensive experience in scalable backend systems.',
    verified: false,
  },
  {
    id: 'f4',
    name: 'Neha Gupta',
    role: 'freelancer',
    avatar: 'https://picsum.photos/seed/neha/200/200',
    location: {
      lat: 26.87,
      lng: 80.95,
      address: 'Aliganj, Lucknow',
      pincode: '226024',
    },
    rating: 4.8,
    skills: ['Elementor', 'WooCommerce', 'PHP'],
    bio: 'WordPress Expert helping local businesses establish their online presence.',
    verified: true,
  },
  {
    id: 'f5',
    name: 'Vikram Malhotra',
    role: 'freelancer',
    avatar: 'https://picsum.photos/seed/vikram/200/200',
    location: {
      lat: 26.84,
      lng: 80.93,
      address: 'Charbagh, Lucknow',
      pincode: '226004',
    },
    rating: 4.9,
    skills: ['Flutter', 'Dart', 'Firebase'],
    bio: 'Mobile App Dev specializing in cross-platform development for Android and iOS.',
    verified: true,
  },
  {
    id: 'f6',
    name: 'Anjali Desai',
    role: 'freelancer',
    avatar: 'https://picsum.photos/seed/anjali/200/200',
    location: {
      lat: 26.88,
      lng: 81.02,
      address: 'Vikas Nagar, Lucknow',
      pincode: '226022',
    },
    rating: 4.8,
    skills: ['Copywriting', 'SEO', 'Blogs'],
    bio: 'Content Specialist & SEO expert driving organic traffic to brands.',
    verified: true,
  }
];

export const mockJobs: Job[] = [
  {
    id: 'j1',
    title: 'E-commerce Website for Local Bakery',
    description: 'Looking for a developer to build a modern Shopify store or custom React site for our bakery in Aliganj.',
    clientId: 'c1',
    budget: 25000,
    category: 'Development',
    type: 'fixed',
    radiusKm: 15,
    location: {
      lat: 26.892,
      lng: 80.942,
      address: 'Aliganj, Lucknow',
    },
    createdAt: new Date().toISOString(),
    status: 'open',
    skillsRequired: ['E-commerce', 'React', 'Payment Integration'],
  },
  {
    id: 'j2',
    title: 'Logo Redesign for Tech Startup',
    description: 'We need a vibrant new logo that reflects our presence in the Lucknow tech ecosystem.',
    clientId: 'c2',
    budget: 8000,
    category: 'Design',
    type: 'fixed',
    radiusKm: 10,
    location: {
      lat: 26.846,
      lng: 81.02,
      address: 'Indira Nagar, Lucknow',
    },
    createdAt: new Date().toISOString(),
    status: 'open',
    skillsRequired: ['Logo Design', 'Vector Art'],
  }
];
